# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy clicsearch

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

    
env:
  AZURE_WEBAPP_NAME: clicsearch
  PYTHON_VERSION: '3.10'
  NODE_VERSION: '18'
  FLASK_APP: 'app/backend/app.py'
  FLASK_ENV: 'production'
  FLASK_DEBUG: 'false' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - name: Set up Node version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Install backend dependencies
        working-directory: ./app/backend
        run: |
          python -m venv backend_env
          source backend_env/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Install frontend dependencies and build frontend
        working-directory: ./app/frontend
        run: |
          npm install
          npm run build

      # - name: Login to Azure
      #   run:
      #     azd login --tenant
    

  deploy:
    runs-on: ubuntu-latest
    needs: build
    # environment:
      # name: 'Production'
      # url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Building web app
        uses: azure/appservice-build@v2
      
      # - name: 'Deploy to Azure Web App'
      #   uses: azure/webapps-deploy@v2
      #   id: deploy-to-webapp
      #   with:
      #     app-name: ${{ env.AZURE_WEBAPP_NAME }}
      #     package: app/backend
      #     slot-name: 'Production'
      #     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      
